import './globals.css'
import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import { Geist } from 'next/font/google'
import { Header } from './components/header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Users Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}  antialiased`}>
        <Toaster richColors />
        <Header />

        {children}
      </body>
    </html>
  )
}
